### PR TITLE
Interactive notebooks in Binder

### PR DESCRIPTION
**Pull request by drphilmarshall**
So close, Boris!

http://mybinder.org/repo/drphilmarshall/daft

Binder gets the following error on the "exoplanets" example. It can make the "classic" PGM, but none of the label text appears. I think binder doesn't have latex...

Anyway, the "examples.ipynb" notebook seems useful, and maybe also the "index.ipynb" which binder uses as its homepage.

> /home/main/anaconda2/lib/python2.7/site-packages/matplotlib/text.py in _get_layout(self, renderer)
>     350         tmp, lp_h, lp_bl = renderer.get_text_width_height_descent('lp',
>     351                                                          self._fontproperties,
> --> 352                                                          ismath=False)
>     353         offsety = (lp_h - lp_bl) \* self._linespacing
>     354 
> 
> /home/main/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py in get_text_width_height_descent(self, s, prop, ismath)
>    2084             fontsize = prop.get_size_in_points()
>    2085             w, h, d = texmanager.get_text_width_height_descent(s, fontsize,
> -> 2086                                                                renderer=self)
>    2087             return w, h, d
>    2088 
> 
> /home/main/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py in get_text_width_height_descent(self, tex, fontsize, renderer)
>     673         else:
>     674             # use dviread. It sometimes returns a wrong descent.
> --> 675             dvifile = self.make_dvi(tex, fontsize)
>     676             dvi = dviread.Dvi(dvifile, 72 \* dpi_fraction)
>     677             try:
> 
> /home/main/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py in make_dvi(self, tex, fontsize)
>     420                      'string:\n%s\nHere is the full report generated by '
>     421                      'LaTeX: \n\n' % repr(tex.encode('unicode_escape')) +
> --> 422                      report))
>     423             else:
>     424                 mpl.verbose.report(report, 'debug')
> 
> RuntimeError: LaTeX was not able to process the following string:
> 'lp'

### CODE REVIEW

**Comment by ixkael** [comment]
Yes it looks like it's not processing the latex for some reason. I searched The Google but didn't find a solution. I am clueless since I've never used binder. Is there a docker configuration file somewhere? If so, we just need to add latex there.
Thanks for putting all this together!

**Comment by drphilmarshall** [comment]
Yeah, I think you can provide a docker config file (with its usual name) in
the repo and binder will do something sensible. It used to ask you to
choose whether you were providing a pip `requirements.txt`, conda
`environment.yml` or docker file, but now it doesn't - so try the docker
one and we'll see what happens...

**Comment by ixkael** [comment]
I finally figured it out - I added a Dockerfile that fixes the mybinder issue. However it requires texlive-full which takes a while to build. But at least latex is rendered!

**Comment by drphilmarshall** [comment]
Rock. On. Sound slike I should elevate my simple comments to an actual
review!

**Pull request merged**
